/// D4rt Interpreter Initialization for Tom CLI.
///
/// This file contains the initialization script that is executed when the
/// D4rt interpreter starts for local script execution in Tom CLI. It sets up:
/// - All necessary imports for Tom Build and Tom Core classes
/// - Global variables for commonly used objects
/// - Access to the `tom` context object
///
/// ## How It Works
///
/// The initialization script is generated by combining:
/// 1. `getImportBlock()` from each bridge package
/// 2. Custom global variable declarations (tom, env, etc.)
/// 3. A `void main() {}` entry point
///
/// ## Usage
///
/// The initialization script is executed once when D4rtInstance is created:
/// ```dart
/// final instance = D4rtInstance.create(workspace: workspace);
/// // Initialization script is executed automatically
/// ```
///
/// ## Difference from VS Code Bridge
///
/// Tom CLI scripts have access to:
/// - `tom` - Full workspace context including project info
/// - `Shell` - Shell command execution
/// - Tom Build and Tom Core classes
///
/// Tom CLI scripts do NOT have access to:
/// - VS Code APIs (use `vscode:` commands to execute in VS Code bridge)
library;

import '../tom_d4rt/dartscript.b.dart' as dartscript_bridges;

/// Global variable assignments for D4rt scripts in Tom CLI.
///
/// These make commonly used objects directly accessible without
/// needing to access them through class static members.
///
/// Available global variables:
/// - `tom` - The global TomContext object
/// - `tomExecutionContext` - The global TomExecutionContext object
/// - `env` - Environment variables map (null if tom is uninitialized)
/// - Platform constants: platformWeb, platformMacos, platformWindows, etc.
/// - Environment constants: defaultTomEnvironment, noTomEnvironment, noTomPlatform
///
/// Note: `tom.project` is null for pre/post-action commands and set
/// to the current project for per-project commands.
///
/// **Important:** Global variables (tom, env, project, platformXxx, etc.) are
/// registered using D4rt's registerGlobalVariable() API, NOT defined here.
/// This allows them to be updated after initialization (e.g., when project
/// context is set by the action executor).
const String cliGlobalVariables = '''
// =============================================================================
// Tom Build Globals
// =============================================================================

// tom, env, project are registered as global variables via registerGlobalVariable()
// They are NOT defined here to avoid shadowing and allow updates.
// Access them directly: tom.workspace, tom.project, env['PATH'], etc.

// Shell utilities for command execution
// Use: Shell.run('dart analyze')
// Use: Shell.runAll(['dart analyze', 'dart test'])

// =============================================================================
// Tom Core Kernel Globals
// =============================================================================

// tomExecutionContext, tomReflector, tomComponent are registered via registerGlobalVariable()

// =============================================================================
// Platform Constants
// =============================================================================

// Platform constants are registered via registerGlobalVariable():
// platformWeb, platformMacos, platformWindows, platformAndroid, 
// platformIos, platformLinux, platformFuchsia

// =============================================================================
// Environment Constants
// =============================================================================

// Environment constants are registered via registerGlobalVariable():
// defaultTomEnvironment, noTomEnvironment, noTomPlatform
''';

/// Gets the import block for CLI initialization.
///
/// Collects import blocks from all bridge packages.
String _getCliImports() {
  return dartscript_bridges.TomBuildCliBridges.getImportBlock();
}

/// Gets the complete initialization script for Tom CLI D4rt execution.
///
/// This script is executed once when the D4rt interpreter starts for
/// an action. It sets up all imports and global variables.
///
/// ## Available After Initialization
///
/// - `tom` - TomContext with workspace, project, projectInfo, etc.
/// - `tom.workspace` - TomWorkspace configuration
/// - `tom.project` - Current project (null for pre/post-action)
/// - `tom.projectInfo` - Map of all projects
/// - `tom.groups` - Group definitions
/// - `tom.actions` - Action definitions
/// - `tom.env` - Environment variables
/// - `env` - Shortcut to environment variables
/// - `Shell.run()` - Execute shell commands
String getCliInitializationScript() {
  return '''
${_getCliImports()}

$cliGlobalVariables

void main() {
  // Initialization complete - D4rt is ready for eval()
}
''';
}

/// Gets just the imports portion of the CLI initialization script.
///
/// Useful when you need to include imports in a custom script.
String getCliImportsOnly() => _getCliImports();

/// Gets just the global variables portion of the CLI initialization script.
///
/// Useful when you need the variable declarations separately.
String getCliGlobalVariablesOnly() => cliGlobalVariables;

/// Gets a script to clear the project context.
///
/// Executed before pre/post-action commands to ensure tom.project is null.
String getProjectClearScript() {
  return '''
${dartscript_bridges.TomBuildCliBridges.getImportBlock()}

void main() {
  // Project context is managed by initializeTomContext/resetTomContext
  // This script just ensures the context is available for eval
}
''';
}

/// Gets a script to prepare for project-level execution.
///
/// This doesn't actually set the project - that's done via initializeTomContext
/// before this script runs. This just ensures imports are available.
String getProjectPrepareScript() {
  return '''
${dartscript_bridges.TomBuildCliBridges.getImportBlock()}

void main() {
  // Project context is set via initializeTomContext before this runs
  // tom.project is now available with the current project
}
''';
}
