/// Build script for d4rt CLI
///
/// Generates version.versioner.dart with build info and compiles the executable.
///
/// Usage:
///   dart run tool/build_d4rt.dart [--install]
///
/// Options:
///   --install    Copy to ~/.tom/bin/ after compilation
///   --version    Set version (default: 1.0.0)
library;

import 'dart:io';

void main(List<String> args) async {
  final install = args.contains('--install');
  final versionIndex = args.indexOf('--version');
  final version = versionIndex >= 0 && versionIndex + 1 < args.length
      ? args[versionIndex + 1]
      : '1.0.0';

  final workspaceRoot = _findWorkspaceRoot();
  if (workspaceRoot == null) {
    stderr.writeln('Error: Could not find workspace root');
    exit(1);
  }

  print('Building d4rt...');

  // Get build info
  final buildTime = DateTime.now().toUtc().toIso8601String();
  final gitCommit = await _getGitCommit(workspaceRoot);

  print('  Version: $version');
  print('  Build time: $buildTime');
  print('  Git commit: $gitCommit');

  // Generate version.versioner.dart
  final versionFile = File(
    '$workspaceRoot/dartscript/tom_dartscript_bridges/lib/src/cli/version.versioner.dart',
  );
  await _generateVersionFile(versionFile, version, buildTime, gitCommit);
  print('Generated: ${versionFile.path}');

  // Compile
  final buildDir = Directory('$workspaceRoot/_build');
  if (!buildDir.existsSync()) {
    buildDir.createSync(recursive: true);
  }

  final result = await Process.run(
    'dart',
    ['compile', 'exe', 'bin/d4rt.dart', '-o', 'd4rt'],
    workingDirectory: buildDir.path,
  );

  if (result.exitCode != 0) {
    stderr.writeln('Compilation failed:');
    stderr.writeln(result.stderr);
    exit(1);
  }

  final outputPath = '${buildDir.path}/d4rt';
  print('Generated: $outputPath');

  // Install if requested
  if (install) {
    final dest = await _getInstallPath();
    final destDir = Directory(dest).parent;
    if (!destDir.existsSync()) {
      destDir.createSync(recursive: true);
    }
    File(outputPath).copySync(dest);
    // Make executable
    await Process.run('chmod', ['+x', dest]);
    print('Installed: $dest');
  }

  print('Done!');
}

String? _findWorkspaceRoot() {
  var dir = Directory.current;
  while (dir.path != dir.parent.path) {
    if (File('${dir.path}/tom_workspace.yaml').existsSync()) {
      return dir.path;
    }
    dir = dir.parent;
  }
  // Fallback: check if we're in the workspace
  final current = Directory.current.path;
  if (current.contains('tom2')) {
    final idx = current.indexOf('tom2');
    return current.substring(0, idx + 4);
  }
  return null;
}

Future<String> _getGitCommit(String workspaceRoot) async {
  try {
    final result = await Process.run(
      'git',
      ['rev-parse', '--short', 'HEAD'],
      workingDirectory: workspaceRoot,
    );
    if (result.exitCode == 0) {
      return (result.stdout as String).trim();
    }
  } catch (_) {}
  return 'unknown';
}

Future<void> _generateVersionFile(
  File file,
  String version,
  String buildTime,
  String gitCommit,
) async {
  final content = '''
// GENERATED FILE - DO NOT EDIT
// Generated by tool/build_d4rt.dart at $buildTime

/// Build version information for d4rt CLI
const String d4rtVersion = '$version';

/// Build timestamp (ISO 8601 format)
const String d4rtBuildTime = '$buildTime';

/// Git commit hash (short form) if available
const String d4rtGitCommit = '$gitCommit';
''';
  await file.writeAsString(content);
}

Future<String> _getInstallPath() async {
  final home = Platform.environment['HOME'] ?? '';
  
  // Detect architecture - using VS Code platform naming convention (hyphens)
  if (Platform.isMacOS) {
    final result = await Process.run('uname', ['-m']);
    final arch = (result.stdout as String).trim();
    if (arch == 'arm64') {
      return '$home/.tom/bin/darwin-arm64/d4rt';
    } else {
      return '$home/.tom/bin/darwin-x64/d4rt';
    }
  } else if (Platform.isLinux) {
    final result = await Process.run('uname', ['-m']);
    final arch = (result.stdout as String).trim();
    if (arch == 'aarch64' || arch == 'arm64') {
      return '$home/.tom/bin/linux-arm64/d4rt';
    } else {
      return '$home/.tom/bin/linux-x64/d4rt';
    }
  } else if (Platform.isWindows) {
    return '$home/.tom/bin/win32-x64/d4rt.exe';
  }
  
  return '$home/.tom/bin/d4rt';
}
